package fr.cozyhouse.cozyHouseQuests.enums;

public enum QuestCondition {
    HOLDRIGHTHAND, HOLDLEFTHAND, HOLDINVENTORY, COMPLETEQUEST, LEVEL, HEART, FOOD, HOLDHELMET, HOLDCHESTPLATE, HOLDLEGGINGS, HOLDBOOTS
}
